# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefeningen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveldrie',
            name='host',
            field=models.CharField(default='127.0.0.1:8000', max_length=255),
        ),
        migrations.AddField(
            model_name='leveleen',
            name='host',
            field=models.CharField(default='127.0.0.1:8000', max_length=255),
        ),
        migrations.AddField(
            model_name='leveltwee',
            name='host',
            field=models.CharField(default='127.0.0.1:8000', max_length=255),
        ),
    ]
