# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oefeningen', '0002_auto_20161006_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelVier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bericht', models.TextField()),
                ('naam', models.CharField(max_length=255)),
                ('host', models.CharField(default='127.0.0.1:8000', max_length=255)),
            ],
        ),
    ]
